### ISSUE TITLE
error upload apk release 

### ISSUE THREAD

**Issue by AhmadNaruto** [amirisback/automated-build-android-app-with-github-action#5]
I don't know if this is a bug or an error in my settings. everything is okay up to the stage of uploading the apk release.

this error showed:
Warning: Unexpected input(s) 'workflowpath', valid inputs are ['name', 'path', 'if-no-files-found', 'retention-days']
Run actions/upload-artifact@v2
Error: Input required and not supplied: path
![Screenshot_20220501_151057](https://user-images.githubusercontent.com/47007634/166136060-74c8caee-2fbe-4bb7-a578-0ef70690ad52.jpg)

**Comment by amirisback** [comment]
Hello, thanks for your report, 

For resolve that issue you must have keystore on (app folder) and keystore script on your build.gradle (app module)

- Keystore Jks Position
https://github.com/amirisback/automated-build-android-app-with-github-action/tree/master/app

- Keystore Script Signing Config sample (this is for build.gradle.kts)
https://github.com/amirisback/automated-build-android-app-with-github-action/blob/master/app/build.gradle.kts

- Official google sources
https://developer.android.com/studio/publish/app-signing

NOTE : If you use build.gradle you can find any source from other project

**Comment by amirisback** [comment]
please recheck your output folder from building app-release

**Comment by AhmadNaruto** [comment]
ahh..thank you

**Comment by AhmadNaruto** [comment]
ah. thanks 😁
